### ISSUE TITLE
Any resources on how to use for MonoGame?

### ISSUE THREAD

**Issue by RamiMorrar** [TheBoneJarmer/TiledCS#15]
I can't find a good resource to write my own Tiled Map to load the MonoGame Pipeline Tool. Any suggestions?

**Comment by TheBoneJarmer** [comment]
Hi @RamiMorrar 

Yes, please read the README. I devoted a special chapter on how to use TiledCS in MonoGame. In short, my colleague, @delightedcat, created a example project to demonstrate how it can be used. I would recommend to ask questions related to MonoGame implementations in his example project repository as he is the expert on the matter. I'm just responsible for TiledCS in general.

With kind regards,
Ruben Labruyere
