### ISSUE TITLE
Visible flag appears to be broken

### ISSUE THREAD

**Issue by alexshaunod** [TheBoneJarmer/TiledCS#16]
The state of the visible flag for layers doesn't appear to match the state of the visible flag in the Tiled Editor or XML.

**Comment by TheBoneJarmer** [comment]
Hi @alexshaunod 

Thank you for reaching out to us. Could you share with us what Tiled version you are using? Also, could you tell us if you are talking about any layer or a specific type of layer? Like tile layers or object layers.

With kind regards,
TheBoneJarmer

**Comment by TheBoneJarmer** [comment]
Hi @alexshaunod 

No need to gather more information. I discovered the bug myself too after some short research. I also fixed it right away and released a new version too. Could you update your nuget package version to 2.2.1 and let me know if things work for you?

With kind regards,
TheBoneJarmer

**Comment by alexshaunod** [comment]
Not quite, Tile Layers appear to have the correct visible state. But objectgroups appear to be defaulting to true. (I have 3 objectgroups of the same name if that helps?)

**Comment by TheBoneJarmer** [comment]
Hi @alexshaunod 

My apologies, you are absolutely correct. I just checked and noticed I indeed forgot to add the same check over there as well. That said, I just did and pushed NuGet package 2.2.2. Can I once more ask you to try again and let me know if it fully works this time?

With kind regards,
Ruben Labruyere

**Comment by alexshaunod** [comment]
Appear to all be working now thanks Ruben!

**Comment by TheBoneJarmer** [comment]
Hi @alexshaunod 

Awesome! And you are very welcome. I am happy I was able to help you out. Have a nice day and have fun coding and mapping. :D

With kind regards,
Ruben Labruyere
