### ISSUE TITLE
Add "Type" property to TiledTileset

### ISSUE THREAD

**Issue by alexshaunod** [TheBoneJarmer/TiledCS#17]
It would be useful if the default Type property was included in the loaded TiledTileset class members after being loaded. If you look in the .tsx file the type is defined alongside the ID within the <tile> tags. E.g <tile id="0" type="HitPolygon">.

I assume these types are usually included in Object definitions instead?

**Comment by TheBoneJarmer** [comment]
Hi @alexshaunod 

Are you talking about the type attribute on a property node or do you mean something different? If so, could you explain to me what you mean?

With kind regards,
Ruben Labruyere

**Comment by alexshaunod** [comment]
If you open up a tileset (tsx) file and select a tile, you will see alongside it's ID it has Type, Width, Height, and in newer versions of Tiled "Probability". I was hoping we could parse the Type property as part of TiledTile.

**Comment by TheBoneJarmer** [comment]
Hi @alexshaunod 

Thank you for the information. I do understand now. I just checked it out with my test map and I do see indeed that a type property was added to the tile node. I can add it, no problem at all.

With kind regards,
Ruben Labruyere

**Comment by TheBoneJarmer** [comment]
Hi @alexshaunod 

I would like to let you know I just pushed NuGet package 2.2.3 which supports the type property of a tile. I decided to release it as a patch since the change itself is very very small. Can you let me know if it works?

With kind regards,
Ruben Labruyere

**Comment by alexshaunod** [comment]
Type seems to come through correctly for me thank you :)

**Comment by TheBoneJarmer** [comment]
Hi @alexshaunod 

Glad to hear! If there is anything else, don't hesitate to open up an issue. Have a nice day and have fun mapping and coding! :D

With kind regards,
Ruben Labruyere
