### ISSUE TITLE
Tile Objects in objectgroup layers currently unusable

### ISSUE THREAD

**Issue by alexshaunod** [TheBoneJarmer/TiledCS#18]
One of my scenes relies on extracting the gid similar to how Tile Layers do it. However I noticed Tile Objects do not have the gid.

In the tmx file, here is an example on how a Tile Object looks inside an object layer:

```
  <object id="1661" gid="496" x="864" y="160" width="32" height="32">
   <properties>
    <property name="ShadowOffset" value="-7"/>
    <property name="Z" type="float" value="11"/>
   </properties>
  </object>
```

You can find the gid value inside the <object>

(apologies for the issue spam, I'm converting my game from TiledSharp to TiledCS and its a bit of a hastle haha)

**Comment by TheBoneJarmer** [comment]
Hi @alexshaunod 

Not a problem at all! I'm happy to help. TiledCS is still rather new on the market compared to other Tiled libraries. That is why there is a good chance that some things are not included yet. And I mean, we are talking about Tiled. It looks basic but is actually really advanced. There is always something new to learn. And last time I spoke to Björn, he told me he had plans for even more awesome stuff so there will always be something TiledCS does not support yet haha

Anyways, I will take a look at it. I do indeed recall being able to use tiles from your tilesets to represent objects. So I'm pretty certain it won't be too difficult. And again, don't feel bad about opening up so many issues. I'm glad you do honestly. That way I learn of stuff that is still missing. :D

With kind regards,
TheBoneJarmer

**Comment by TheBoneJarmer** [comment]
Hi @alexshaunod 

I would like to let you know that I just added support for object gids in the develop branch. Will release a new version soon. :)

With kind regards,
TheBoneJarmer

**Comment by TheBoneJarmer** [comment]
Oops, did not meant to close it this fast haha

**Comment by TheBoneJarmer** [comment]
Hi @alexshaunod 

I just pushed NuGet package 2.3.0, could you pull it and tell me if it works now for you? This includes both your requested changes.

With kind regards,
TheBoneJarmer

**Comment by TheBoneJarmer** [comment]
Hi @alexshaunod 

I have not heard back from you so I am going to assume everything works for you. Closing the ticket.

With kind regards,
TheBoneJarmer
