### ISSUE TITLE
Missing Properties definition for Object Layers and Tile Layers

### ISSUE THREAD

**Issue by alexshaunod** [TheBoneJarmer/TiledCS#19]
You can define custom properties for Object Layers/ Tile Layers themselves, similar to how you can  define custom properties on Maps:

```
 <objectgroup id="38" name="ForegroundShader">
  <properties>
   <property name="EffectName" value="Fog"/>
  </properties>
 </objectgroup>
```

My previous TiledSharp implementation relied on this for certain layer wide parameters, would be handy to have in TiledCS

**Comment by TheBoneJarmer** [comment]
Hi @alexshaunod 

I said this already in the other issue of yours, but for the sake of organizing I'll mention it here as well. I just pushed NuGet package 2.3.0, this includes both your requested changes. Let me know if it works for you :)

With kind regards,
TheBoneJarmer

**Comment by alexshaunod** [comment]
The changes seems to be working fine, however I noticed the properties on my tiles are now null?

**Comment by TheBoneJarmer** [comment]
Hmm.. That's odd. But I cannot seem to reproduce the issue. Could you send me your tsx file, please? If possible with tileset? Than I can compare your tileset with mine and see what is the difference.

**Comment by alexshaunod** [comment]
Here is an example of a tsx file I'm using:

```
<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.5" tiledversion="1.6.0" name="collision_demo" tilewidth="32" tileheight="32" tilecount="8" columns="4">
 <image source="../../graphics/maps/tilesets/demo/collision_demo.png" width="128" height="64"/>
 <tile id="0" type="HitPolygon">
  <properties>
   <property name="Point1X" type="int" value="0"/>
   <property name="Point1Y" type="int" value="0"/>
   <property name="Point2X" type="int" value="32"/>
   <property name="Point2Y" type="int" value="0"/>
   <property name="Point3X" type="int" value="32"/>
   <property name="Point3Y" type="int" value="32"/>
  </properties>
  <objectgroup draworder="index" id="2">
   <object id="2" x="0" y="0">
    <polygon points="0,0 32,0 32,32"/>
   </object>
  </objectgroup>
 </tile>
 <tile id="1" type="HitSquare">
  <properties>
   <property name="Point1X" type="int" value="0"/>
   <property name="Point1Y" type="int" value="0"/>
   <property name="Point2X" type="int" value="32"/>
   <property name="Point2Y" type="int" value="0"/>
   <property name="Point3X" type="int" value="0"/>
   <property name="Point3Y" type="int" value="32"/>
   <property name="Point4X" type="int" value="32"/>
   <property name="Point4Y" type="int" value="32"/>
  </properties>
  <objectgroup draworder="index" id="2">
   <object id="2" x="0" y="0" width="32" height="32"/>
  </objectgroup>
 </tile>
 <tile id="2" type="HitPolygon">
  <properties>
   <property name="Point1X" type="int" value="0"/>
   <property name="Point1Y" type="int" value="0"/>
   <property name="Point2X" type="int" value="0"/>
   <property name="Point2Y" type="int" value="32"/>
   <property name="Point3X" type="int" value="32"/>
   <property name="Point3Y" type="int" value="32"/>
  </properties>
  <objectgroup draworder="index" id="2">
   <object id="4" x="0" y="0">
    <polygon points="0,0 0,32 32,32"/>
   </object>
  </objectgroup>
 </tile>
 <tile id="4" type="HitPolygon">
  <properties>
   <property name="Point1X" type="int" value="0"/>
   <property name="Point1Y" type="int" value="0"/>
   <property name="Point2X" type="int" value="32"/>
   <property name="Point2Y" type="int" value="0"/>
   <property name="Point3X" type="int" value="0"/>
   <property name="Point3Y" type="int" value="32"/>
  </properties>
  <objectgroup draworder="index" id="2">
   <object id="3" x="32" y="0">
    <polygon points="0,0 -32,0 -32,32"/>
   </object>
  </objectgroup>
 </tile>
 <tile id="5" type="HitPolygon">
  <properties>
   <property name="Point1X" type="int" value="32"/>
   <property name="Point1Y" type="int" value="0"/>
   <property name="Point2X" type="int" value="0"/>
   <property name="Point2Y" type="int" value="32"/>
   <property name="Point3X" type="int" value="32"/>
   <property name="Point3Y" type="int" value="32"/>
  </properties>
  <objectgroup draworder="index" id="2">
   <object id="2" x="32" y="0">
    <polygon points="0,0 0,32 -32,32"/>
   </object>
  </objectgroup>
 </tile>
</tileset>
```

**Comment by TheBoneJarmer** [comment]
Hi @alexshaunod 

Thanks for sharing your tileset. Now, I copied it and loaded it locally and checked it but it all seems to work for me. Side not here, the objectgroup within a tile has no support yet. But I have to update TiledCS anyway for support for Tiled 1.7 so this will be included.

Anyways, as I can't reproduce the issue locally. Can you share what TiledCS version you are using right now? To make sure we use the same, it should be 2.3.0. Also, could you share the piece of code where you load the tileset and try to parse it?

With kind regards,
TheBoneJarmer

**Comment by alexshaunod** [comment]
I'm parsing a "TiledTile" which I fetch from "TiledTileset". The .properties are what appear as null.

I'm using 2.3.0

**Comment by TheBoneJarmer** [comment]
Hi @alexshaunod 

Thanks for the info. In that case I'm lost. I just tried again loading your tileset file to be absolutely certain, which always load the properties of a tile successfully. I don't understand what could be going wrong.

@delightedcat
Could you help me out with this one? I would like you to pull the same NuGet version and load his tileset. Perhaps there is some caching issue at my side, or something else. But having some fresh view on the matter may help.

With kind regards,
TheBoneJarmer

**Comment by delightedcat** [comment]
Thanks for reaching out, I'm going to have a closer look at this once I get home from work.

@alexshaunod To clarify: Are you having issues with the tile properties under the tileset tile level, or the properties under the object/tile layer level?

**Comment by TheBoneJarmer** [comment]
@delightedcat 

Allow me to answer that question. The issue he experiences is with the TiledTile.properties array. It seems that it worked before my changes and now it does not. But I can't seem to reproduce that.

@alexshaunod 
Which reminds me. Could you uninstall version 2.3.0 and install the previous one? And could you tell me if the tile properties parsing still works for you in that version?

**Comment by delightedcat** [comment]
Thank you, @TheBoneJarmer!

After setting up a quick test, I can conclude that parsing of the properties element is working as intended. The referenced TiledCS version in my testing environment is `2.3.0`. Have a look at the used code below:
```cs
using System;
using TiledCS;
...
var tileset = new TiledTileset("collision_demo.tsx");
Console.WriteLine(tileset.Name);

foreach (TiledTile tile in tileset.Tiles)
{
    Console.WriteLine(tile.properties);
    Console.WriteLine("Not Null: {0}", tile.properties != null);
}
```
This returns the following output in the console:
```
collision_demo
TiledCS.TiledProperty[]
Not Null: True
...
TiledCS.TiledProperty[]
Not Null: True
```
As can be seen, each `properties` field returns an array of `TiledPropery` that is not `null`.

@alexshaunod Are you able to replicate the above code in your personal environment? It seems to me that there is something else that acts as a bother. If all else fails, could you show us the code you're using to load everything up? The goal here is to get as many details as possible to figure out where this issue is coming from.

**Comment by alexshaunod** [comment]
UPDATE: Apologies for this, did some more investigating after work and it seems to be an issue with how Tiled saved my old layers. Creating a new layer with the tiles works for me now! :)
