### ISSUE TITLE
Support Tiled 1.7

### ISSUE THREAD

**Issue by TheBoneJarmer** [TheBoneJarmer/TiledCS#20]
While I was busy at work, a couple of new Tiled versions were released. With 1.7 being the current one. I support Tiled 1.5. so far but clearly need to put some effort into supporting Tiled 1.7.

**Comment by Bryan-Legend** [comment]
I've added infinite layer support in #25

**Comment by TheBoneJarmer** [comment]
Eventually added support for Tiled version **1.8.4**.
