### ISSUE TITLE
Type of tiledLayer.offsetX and tiledLayer.offsetY should be double instead of int

### ISSUE THREAD

**Issue by Bryan-Legend** [TheBoneJarmer/TiledCS#24]
Got a parse error in ParseLayer because the offset for an image layer was not a whole number.

Change it to this:
`                if (attrOffsetX != null) tiledLayer.offsetX = double.Parse(attrOffsetX.Value);
                if (attrOffsetY != null) tiledLayer.offsetY = double.Parse(attrOffsetY.Value);
`

**Comment by Bryan-Legend** [comment]
Fixed in #25

**Comment by TheBoneJarmer** [comment]
Hey @Bryan-Legend 

Sorry for the late reply. I fixed this along with your request for parallax support. I did not use a double in the end but a float because I have done so everywhere else. Therefore this will be fixed with the next major version.

With kind regards,
TheBoneJarmer
