### ISSUE TITLE
"Background Color" map property missing

### ISSUE THREAD

**Issue by Goodlyay** [TheBoneJarmer/TiledCS#27]
Hello again!
As the title states, the TiledMap property "backgroundcolor" (as it is written in the .tmx file) is not available through TiledCS.
I'm not sure how this data should be represented in the class, but at least for my purposes it doesn't matter how it is stored as long as I can access it.

**Comment by Goodlyay** [comment]
My temporary workaround does this 
![image](https://user-images.githubusercontent.com/7892772/139576405-924c7b2e-5bd5-4412-9dff-efab2e9ca04d.png)
But it is obviously not acceptable to use Unity color here so I didn't make a pull request.

**Comment by TheBoneJarmer** [comment]
Hey @Goodlyay 

Thanks for opening up an issue. Will give it  a look today. Seems pretty straightforward to do. My apologies for the inconvience.

With kind regards,
TheBoneJarmer

**Comment by TheBoneJarmer** [comment]
Hi @Goodlyay 

Since the change was this small I already went ahead and pushed a new package under version 2.4.2. It includes only a change for the missing support for the backgroundcolor property. So hence the patch release. Let me know if it works for you. :)

With kind regards,
TheBoneJarmer

**Comment by Goodlyay** [comment]
Perfect, works great. Thanks!
