### ISSUE TITLE
Loading a TiledMap when the map has tiles with rotations results in an Int32 OverflowException

### ISSUE THREAD

**Issue by Goodlyay** [TheBoneJarmer/TiledCS#3]
I'm using TiledCS as an easy way to get data from Tiled maps, since I'm building my world out of 3D object tiles and wanted an easy way to edit maps, and it's been very helpful so far (thank you!), but, as the title states, I ran into a problem.

I'm guessing this is due to the tile flipping being stored in bits 32, 31, and 30, as specified [here](https://doc.mapeditor.org/en/stable/reference/tmx-map-format/#tile-flipping). However the tiles are read as signed ints, which can't hold values that large.

Here is an example of the error I get. Using Unity 2019.4.17f1 if it's relevant. I can supply the entire project if needed.

OverflowException: Value was either too large or too small for an Int32.
System.Number.ParseInt32 (System.String s, System.Globalization.NumberStyles style, System.Globalization.NumberFormatInfo info) (at <9577ac7a62ef43179789031239ba8798>:0)
System.Int32.Parse (System.String s) (at <9577ac7a62ef43179789031239ba8798>:0)
TiledCS.Extensions+<>c.<AsIntArray>b__1_0 (System.String x) (at Assets/Scripts/TiledCS/Extensions.cs:26)
System.Linq.Enumerable+SelectArrayIterator\`2[TSource,TResult].ToArray () (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
System.Linq.Enumerable.ToArray[TSource] (System.Collections.Generic.IEnumerable\`1[T] source) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
TiledCS.Extensions.AsIntArray (System.String[] src) (at Assets/Scripts/TiledCS/Extensions.cs:26)
TiledCS.TiledMap.ParseLayers (System.Xml.XmlNodeList nodeListLayers, System.Xml.XmlNodeList nodeListObjGroups) (at Assets/Scripts/TiledCS/TiledMap.cs:182)
TiledCS.TiledMap.Parse (System.String xml) (at Assets/Scripts/TiledCS/TiledMap.cs:116)
Rethrow as TiledException: Unable to parse xml data, make sure the xml data represents a valid Tiled map
TiledCS.TiledMap.Parse (System.String xml) (at Assets/Scripts/TiledCS/TiledMap.cs:120)
TiledCS.TiledMap..ctor (System.String path) (at Assets/Scripts/TiledCS/TiledMap.cs:83)
Game.Start () (at Assets/Scripts/Game.cs:29)

**Comment by Goodlyay** [comment]
I should probably provide an example map as well. Here is the one I'm trying to load. 
[map.zip](https://github.com/TheBoneJarmer/TiledCS/files/6214744/map.zip)
And this tile is an example culprit:
![image](https://user-images.githubusercontent.com/7892772/112702501-f0002000-8e50-11eb-8456-d3bcec68522a.png)

**Comment by TheBoneJarmer** [comment]
Hi there

First of all, thank you for the kind words. I really appreciate it! As for your issue, TiledCS does not cover all Tiled features as it was based on generic requirements. To be honest, the whole tile flipping thing does not ring a bell to me.  So this would require a bit of research on my end. But I'll take a look at it, no worries.

Also, thanks for sharing the map. I was typing this comment when you sent yours and I was about to ask for the map itself. I'll take a look at it end let you know. :)

With kind regards,
TheBoneJarmer

**Comment by TheBoneJarmer** [comment]
I had a quick look and I agree with your analysis. The value is bigger than the max of an int. Will have to look for a good solution but I think the easiest one would be changing the ints to uints. But I'll take a look tomorrow or Sunday. It is 00:46 in my area now so I gotta catch some sleep.  :)

**Comment by Goodlyay** [comment]
Thanks for the quick response. For now I'll probably try changing it to uint or keep as int (since having negative values can be useful...), but remove the rotation flags right as it's parsed and store those flags in a parallel array for easy access later.

**Comment by TheBoneJarmer** [comment]
Hey, sorry for the late reply. I just merged your PR and will do a release soon as Tiled 1.5 has been released. Thanks a lot for your patience. If there is anything else, let me know. When the release is done I will close this issue.

**Comment by TheBoneJarmer** [comment]
Alright, I made my changes and pushed them to develop. I moved your logic a bit here and there as you will see. Basically I just moved your logic to the TiledMap class and divided the GetRotations in multiple methods. I realized that while the official term is tile rotations, the editor labels them as flipping, which could be confusing. 

Therefore I created new methods which are called IsTileFlippedHorizontally, IsTileFlippedVertically and IsTiledFlippedDiagonally. On top of that I renamed the variables x and y to tileHor and tileVert as the x and y positions are literally on-screen vectors while these methods require the horizontal position and vertical position on the tile grid. I hope these changes make that a bit more clear. Other than that I kept the logic intact. I will do a release in a couple of minutes and close this issue later today.

**Comment by Goodlyay** [comment]
If I'm understanding correctly, you've renamed x and y to tileHor and tileVert because x and y is used to mean a precise pixel position on-screen? As opposed to the count of rows or columns a tile is located at.

**Comment by TheBoneJarmer** [comment]
Yes, precisely. When you place objects in the editor you will notice that in the left pane, the x and y positions are floating points which represent the actual position in pixels. While the arguments these methods need are not those values but the horizontal and vertical position on the grid. Those can be located in the footer of the editor. But I was worried users would mistake the pixel precise vectors used in objects with the arguments required for the methods since you don't see those floating point values when placing tiles. I hope that clarifies it a bit.

The same goes for width and height by the way. The map's width is in tiles horizontally while an object width is in pixels. They are both called width but use different units of measurements. Which reminds me that I also need to adjust that difference as well in one of the methods. But still, I can imagine it could be a little confusing to those using this library for the first time.
