### ISSUE TITLE
Add "Parallax Origin" parameter to Object Layers

### ISSUE THREAD

**Issue by odeycodey** [TheBoneJarmer/TiledCS#33]
As part of Tiled 1.5, they added support for Parallaxing object layers, would be handy for devs to have access to the "Parallax Origin" property they've added under the object layer (see here: https://www.mapeditor.org/2021/03/23/tiled-1-5-0-released.html)

**Comment by TheBoneJarmer** [comment]
Hey

I am sorry for the late reply. I just added support for parallax origin for both the layers **and** map. It will be included with the next major release.

With kind regards,
TheBoneJarmer
