### ISSUE TITLE
Infinite layer support

### ISSUE THREAD

**Issue by TheBoneJarmer** [TheBoneJarmer/TiledCS#52]
A while ago a pull request got opened for the support of infinite layers. I had to reject the pull request but the need for it is valid and therefore I should look into adding support for it.

**Comment by TheBoneJarmer** [comment]
@Bryan-Legend fyi

**Comment by Bryan-Legend** [comment]
Very cool!

**Comment by TheBoneJarmer** [comment]
Hey @Bryan-Legend 

Wanted to let you know I implemented support for infinite layers. It will become available with the next minor release.

With kind regards,
TheBoneJarmer
