### ISSUE TITLE
tiled 1.9?

### ISSUE THREAD

**Issue by monogamefan** [TheBoneJarmer/TiledCS#56]
Hi

I see tiled 1.8.4 is going to be supported but now there is Tiled 1.9 alpha
Do you know if there is another change in the format or will tiledcs still work with 1.9?
I read automapping is changed (or something I don't use)

**Comment by TheBoneJarmer** [comment]
Hi

I am going to look at Tiled 1.9 support when the alpha release has become the next stable one. Version 1.8.4. is the latest stable as to date.

With kind regards,
TheBoneJarmer
