### ISSUE TITLE
feature request: collisions using collision editor

### ISSUE THREAD

**Issue by monogamefan** [TheBoneJarmer/TiledCS#58]
Hi

Do you think you can implement collisions of Tiled by using the collision editor?
I believe they are stored in the tilesets and define collisions for each tile type.
In the tilemap they are then used by looking at the tileset.

I don't know if this is possible and if this is usable in an engine.
This is where the example project comes in handy to find out ;-)

**Comment by TheBoneJarmer** [comment]
Hi

They are already supported as of the latest release. They are stored in the `TiledTileset.Tiles.objects` array.

With kind regards,
TheBoneJarmer
