### ISSUE TITLE
TiledObject.rotation should be a float not an int.

### ISSUE THREAD

**Issue by Bryan-Legend** [TheBoneJarmer/TiledCS#61]
Change ParseObjects as well.

`if (node.Attributes["rotation"] != null)
                {
                    obj.rotation = float.Parse(node.Attributes["rotation"].Value);
                }`

**Comment by TheBoneJarmer** [comment]
Hey

Sorry for the late reply. I will fix this asap but my current priority lies with my new TeamCity server and some c++ projects. I hope to be able to automate builds and releases in the near future, including the ones for TiledCS.

With kind regards,
TheBoneJarmer

**Comment by TheBoneJarmer** [comment]
Hi @Bryan-Legend 

I wanted to let you know I fixed this just now. It will become available within the next minor release.

With kind regards,
TheBoneJarmer

**Comment by Bryan-Legend** [comment]
Thanks!
