### ISSUE TITLE
Incorrect index formula in readme

### ISSUE THREAD

**Issue by awebmekhilef** [TheBoneJarmer/TiledCS#78]
Hey.

Your formula for calculating the index given x and y is supposed to be
`(y * _tileLayer.width) + x` 
instead of 
`(y * _tileLayer.height) + x`.

**Comment by TheBoneJarmer** [comment]
You are absolutely right, well spotted!

**Comment by TheBoneJarmer** [comment]
Updated readme in develop branch, change will be available with next release.
