### ISSUE TITLE
Parse Tiled objects from memory

### ISSUE THREAD

**Issue by jorolf** [TheBoneJarmer/TiledCS#8]
Currently this library only supports loading maps and tilesets directly from disk. In my project however I store multiple files in an archive and can't access them directly through a path. The Tiled objects already contain a private ``Parse`` method which could be exposed to support loading from e.g. a ``string`` object.

**Comment by TheBoneJarmer** [comment]
Hi @jorolf 

You are correct, it does not yet support this. I don't think it is a bad idea to do it. Be aware though it would only be for the TMX/TSX format. I already had thoughts to add a constructor for streams as well. Might as well do that too while I'm at it.

**Comment by TheBoneJarmer** [comment]
I just released a new version, 2.1.1, which now allows the manual parsing of the xml data for both maps and tilesets. Let me know if this works for you.

**Comment by jorolf** [comment]
Yes, the loading works as expected.

**Comment by TheBoneJarmer** [comment]
Sweet, great to hear!
