### ISSUE TITLE
replace TiledProperty.type with enum 

### ISSUE THREAD

**Issue by BBQGiraffe** [TheBoneJarmer/TiledCS#83]
currently TiledProperty.type is a string, this makes using it quite ugly, could probably use Enum.TypeParse if you convert the type string to uppercase(since int, object, bool, and string are C# types and thus can't be used for enums), then if TryParse fails the type could just default to String

**Comment by TheBoneJarmer** [comment]
Hey @BBQGiraffe 

Thanks for the suggestion! I think it is a good idea. As a matter of fact, I thought I already done this as I replaced string fields not that long ago with an enum where possible.

With kind regards,
TheBoneJarmer

**Comment by TheBoneJarmer** [comment]
Hey @BBQGiraffe 

I would like to let you know I just added support for this in the develop. This change will be available with the next release.

With kind regards,
TheBoneJarmer

**Comment by TheBoneJarmer** [comment]
Hi @BBQGiraffe 

I would like to let you know I just released TiledCS 3.3.0, this version includes this change.

With kind regards,
TheBoneJarmer
