### ISSUE TITLE
Issues retrieving parallax x/y factors from a TiledLayer

### ISSUE THREAD

**Issue by Frankfires** [TheBoneJarmer/TiledCS#85]
While being able to retrieve other layer properties from my TiledLayers strangely enough TiledLayer.layer.parallaxX/Y have both always returned 0 for me, which is strange since the default values of the parallax scrolling factors are set to 1. Inside of my .tmx map file I can see the parallax scale factors set for each of my layers and it seems to be correct
![image](https://user-images.githubusercontent.com/67832033/185534489-cc7e8fa9-d1b9-4086-bd0f-3f3c89afaf4a.png)
![image](https://user-images.githubusercontent.com/67832033/185534818-be404b68-a90e-4477-9c4f-9f723ad6bd6e.png)
![image](https://user-images.githubusercontent.com/67832033/185534797-6e98294e-5d7a-4099-9e81-68ec08bf85f1.png)
![image](https://user-images.githubusercontent.com/67832033/185534871-04ff6c95-49bf-4b20-949d-b9e9cc27e141.png)

**Comment by TheBoneJarmer** [comment]
Hey

Thanks for reporting! I will have a look at it.

With kind regards,
TheBoneJarmer

**Comment by TheBoneJarmer** [comment]
Hey

I just learned that I wrongly mapped the parallaxX and parallaxY attribute. Fucked that one up pretty good ghehe. Made a patch and hopefully within a few minutes the new NuGet package is available. :D

With kind regards,
TheBoneJarmer

**Comment by TheBoneJarmer** [comment]
Oh fuck me haha, was not even aware of that. My apologies! And thank you for letting me know. I will correct that and send a new patch on your way. :)

**Comment by TheBoneJarmer** [comment]
The new NuGet has been published in the meantime. The new version is 3.2.3.

**Comment by Frankfires** [comment]
Tile/object layers are working like charms, awesome appreciate you fixing this 👍 
( I think you just need to touch up on image layers, still getting 0 from both parallax values :P )
![image](https://user-images.githubusercontent.com/67832033/185708309-9eed0b02-193a-4c13-94d6-de8c02e479e3.png)
![image](https://user-images.githubusercontent.com/67832033/185708339-71cabae2-f455-4cb1-b925-0224e8934383.png)

**Comment by TheBoneJarmer** [comment]
Hey

Glad to hear!! And thanks for pointing that one out. I made some changes on develop just now that fixes that, added support for the class attribute on a layer (heck, never knew it was possible lol) and done rid of some warnings. I'm cool with releasing another patch but if you don't need this asap I'd rather wait till I got a bunch of stuff again. D:

With kind regards,
TheBoneJarmer

**Comment by Frankfires** [comment]
A quick patch would be greatly appreciated around now but I understand that releasing small tiny minimal patches with very little changes isn't ideal, your call.

**Comment by TheBoneJarmer** [comment]
Than I'll do it. I was not sure you meant you just noticed or that you actually needed it right now. But it seems the latter is the case. Hence I just pushed out a new release. I already got a notification from TeamCity that the build succeeded so within a couple of minutes the NuGet package should be available. :)

Mind you, it is not a patch this time but a minor release because I changed the property type string to an enum as requested by someone else. You might need to change that as well.

**Comment by TheBoneJarmer** [comment]
Hey @Frankfires 

Just to be certain, you mentioned things work flawlessly in the other issue. Does that mean this one is solved for you as well?

With kind regards,
TheBoneJarmer

**Comment by Frankfires** [comment]
Yes, I am now able to retrieve parallax values from image layers, thanks for the fix :D

**Comment by TheBoneJarmer** [comment]
Awesome 😎
