### ISSUE TITLE
Support tilesets based on a collection of images

### ISSUE THREAD

**Issue by jorolf** [TheBoneJarmer/TiledCS#9]
Tiled supports tilesets that consist of one image per tile instead of one large tileset image. These are encoded through a image attribute (see [here](https://doc.mapeditor.org/en/stable/reference/tmx-map-format/#tile)).

**Comment by TheBoneJarmer** [comment]
Hi @jorolf 

I have to admit I didn't knew about that feature. I don't think it would be a problem to support it though. As I understood from the docs, I would have to define a new class called Image and use it as type for a field the Tile class. Still, it would be nice to be able to test it. Could you be so kind to share an example so I can see what it is you are trying to accomplish? Thanks!

**Comment by jorolf** [comment]
I've pushed my code to this repository: https://github.com/jorolf/osu-framework-tiled

The tileset I've mentioned is this one: https://github.com/jorolf/osu-framework-tiled/blob/master/OsuFrameworkTiled.Tests/Resources/Tilesets/default.tsx

Running the test project in the repository should open a window with a test scene however it crashes before that due to "broken" XML (The file in question was created by the tiled editor). Not sure if that is related to this though...

**Comment by TheBoneJarmer** [comment]
I finally found some time to work on this and used your tileset for testing. With the new version, 2.1.1, you should be able to load your tileset without an issue. Fun fact, when I loaded your tileset first I also got an exception. That was a mistake from my end as I assumed the Image node was always available. 

However, that apparently is not the case when you create a tileset with individual tile images. Hence the error message you got. In any case, let me know if the new version works for you!

**Comment by jorolf** [comment]
Everything seems to work, I can access the single images and it doesn't crash anymore.
